language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
script:
- mvn clean install
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: qEbj2l5fsNJDKiileVe8gFIqn2osCq611pRmrF4EEpVeVvwxZirqnDE/TkS+j8Jy2N4gs38051jG8gyxIeH1CNAgJBpaCHx+bw8AGWtU2ZB+YutUsNZuOwTY9ss5CcWALAe1YxwBXwsjw97ZvzC2MhdEQLnn8SenH+aQxeNR7FE+Hun/DmQ3ggq5WRQXzOaiIdCx56A0RJJu9DfzmBByv28ThONDs/+/+eqUzfK+XOHsl43s+hVf8gnADMTYOcU6WYpUD340K/5bSN6d1BBYM7crqC8E/k8Os9sSoq5rFVdAmjPBhUSxhUNAINFVPH/9aSPsUBfo0sbjyDCDS7Y75vE4FxXmAi/KUPsmxilDtyUQfhGEggOYDqqQZ+CugiVfJKAYvOLaWO11otrWCydPf1gdot457Xuab7NmrQeny/xyM6rgbrxIHfpc18I7RbNz5y1j9f5GuckK/zXfXm2VTNwfOg3p+Wbz/XE0wucoJR+4gk3sy0hOsV5bLYGpVmcTlJF36w18gRTZVC+APjtqAjies7KBRICVOGMu29vTdyauF5t5EdqPnOlnu90mnYX3zQQL6ni4hL7TCsUu0OCs1dT8N1aIxJ0I08HAHO0Tg+89ODilEnnotPBZpFwEBM0isrfaOw0S7EWPbbhZ/9Qi6aCYNjltGlqasjMqdraq4rI=
    on_success: never
    on_failure: always
branches:
  only:
  - master
